export const transitionTable = [
  // state 0
  [1, 2, 3, 4, 5, 6, 9, 12, 15, 16, 17, 18, 19, 20, 22, 0, 27, "error", 27],
  // state 1
  [
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
    "accept ;",
  ],
  // state 2
  [
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
    "accept +",
  ],
  // state 3
  [
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
    "accept *",
  ],
  // state 4
  [
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
    "accept (",
  ],
  // state 5
  [
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
    "accept )",
  ],
  // state 6
  [8, 8, 8, 8, 8, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, "error", 8, 8],
  // state 7
  [
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
    "accept ==",
  ],
  // state 8
  [
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
    "accept = back",
  ],
  // state 9
  [11, 11, 11, 11, 11, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, "error", 11, 11],
  // state 10
  [
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
    "accept >=",
  ],
  // state 11
  [
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
    "accept > back",
  ],
  // state 12
  [14, 14, 14, 14, 14, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, "error", 14, 14],
  // state 13
  [
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
    "accept <=",
  ],
  // state 14
  [
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
    "accept < back",
  ],
  // state 15
  [
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
    "accept if",
  ],
  // state 16
  [
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
    "accept else",
  ],
  // state 17
  [
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
    "accept then",
  ],
  // state 18
  [
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
    "accept int",
  ],
  // state 19
  [
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
    "accept char",
  ],
  // state 20
  [21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 20, 20, 21, "error", 21, 21],
  // state 21
  [
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
    "accept id back",
  ],
  // state 22
  [26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 22, 26, "error", 23, 26],
  // state 23
  [
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    24,
    "error",
    "error",
    "error",
    "error",
  ],
  // state 24
  [25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 24, 25, "error", 25, 25],
  // state 25
  [
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
    "accept decimal back",
  ],
  // state 26
  [
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
    "accept number back",
  ],
  // state 27
  [
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
    "accept EOF",
  ],
  // state 28
  [
    "error",
    "error",
    "error",
    "error",
    "error",
    29,
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
    "error",
  ],
  // state 29
  [
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
    "accept !=",
  ],
];
